### ISSUE TITLE
Pretty-printing

### ISSUE THREAD

**Issue by epost** [statebox/cql#71]
# Current situation
Output looks something like this:
```
algebra
"E" (2)
-------------
"e"."f": "f" = "e", "a1" = Right ("e"."f","a2"),"a2" = Right ("e"."f","a2")
"e": "f" = "e"."f", "a1" = Right ("e","a2"),"a2" = Right ("e","a2")
```
Here, `algebra` is a section heading, and `show`-like output, such as `Right ("e","a2")` is mixed with pretty-printed output like the section heading and `-------`.

# TODO
- [x] indent section bodies; currently, we have things like the following, where :
- [ ] `-> String` functions should distinguish between `pretty-printing` and `show`, which should be the inverse of `read`.
- [x] We'll also want to consider some annotated output format like XML, with one obvious use case being to produce HTML.

Ryan's suggestions:
 - [ ] make `TTerm` (in `Instance.hs`) a newtype with a custom `Show`
 - [x] in `Show Term` (in `Term.hs`) we can strip quotes from printed strings using filter, provided the quotes aren't needed (e.g., no spaces) 

Fix `Show` instances:

- [x] `Schema`
- [x] `Entity`
- [ ] `Attribute`
- [x] `Instance`
- [x] `Algebra`
- [x] `Term`
- [x] `Typeside`
- [ ] `Mapping`
- [ ] `Query`
- [ ] `Transform`
- [ ] TODO all the `XxxEx` and `XxxRaw` ones
